text:
        dc.b "            "
        dc.b "            "
        dc.b "LIKE A CANDY"
        dc.b "            "
        dc.b "   FLUSH    "
        dc.b "  KNITTED   "
        dc.b " THIS MERRY "
        dc.b " ATARI VCS  "
        dc.b "  \K INTROQ "
        dc.b " SOMETIMES  "
        dc.b " LIFE JUST  "
        dc.b "TASTES LIKE "
        dc.b "  A CANDY   "
        dc.b "            "
        dc.b "  WELCOME   "
        dc.b "  ON BOARD  "
        dc.b "  TO CLOUQ  "
        dc.b "CONTRIBUTING"
        dc.b "  TO THIS   "
        dc.b " TRIBUTE TO "
        dc.b "SHADOW OF GP"
        dc.b "            "
        dc.b "  CREDITS   "
        dc.b "GFX[ CLOU   "
        dc.b "MSX[ GLAFOUK"
        dc.b "CDZ[ FLEWWW "
        dc.b "            "
        dc.b " GREETZ TO  "
        dc.b "ALTAIR      "
        dc.b "       BOCK "
        ;; dc.b "   BOMB     "
        dc.b "BOOZ DESIGN "
        dc.b "    CLUSTER "
        ;; dc.b "COCOON      "
        dc.b " COOKIE CREW"
        dc.b "DENTIFRICE  "
        ;; dc.b "  DUNE      "
        dc.b "    GENESIS "
        dc.b "    PROJECT "
        dc.b "GOBLINISH   "
        dc.b "HOOY]PROGRAM"
        dc.b "   JAC      "
        dc.b "LABORATOIRE "
        dc.b "PROUT       "
        dc.b "MYSTIC BYTES"
        dc.b "     NOICE  "
        dc.b "PLANET JAZZ "
        ;; dc.b "  POPSY TEAM"
        dc.b "RBBS        "
        dc.b "  SECTOR ONE"
        dc.b "UP ROUGH    "
        dc.b "VITAL MOTION"
        dc.b "       X]MEN"
        dc.b "AND YOU ALL "
        dc.b 0,"           "
	dc.b "            "
